### ISSUE TITLE
java -jar BundleDecompiler.jar decompile       --in=MEPWLApp-umeng-dev-release.aab   --out=debug Input AppBundle path: MEPWLApp-umeng-dev-release.aab Exception in thread "main" java.lang.NullPointerException 	at java.io.File.<init>(File.java:277) 	at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:82) 	at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:38)

### ISSUE THREAD

**Issue by chengcl** [TamilanPeriyasamy/BundleDecompiler#2]
java -jar BundleDecompiler.jar decompile       --in=MEPWLApp-umeng-dev-release.aab   --out=debug
Input AppBundle path: MEPWLApp-umeng-dev-release.aab
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:82)
	at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:38)

I‘m try unpack aab. but  java.lang.NullPointerException happen. can you tell be why? thanks

**Comment by prasannakumark** [comment]
@chengcl ,

Is this issue got resolved? Still, I'm facing the same issue

`java -jar BundleDecompiler-0.0.1.jar d --in=bundle.aab --out=output_dir
Input AppBundle path: bundle.aab
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:80)
	at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:36)`

**Comment by jgmGit** [comment]
@prasannakumark @chengcl  how did you manage to fix that error ?
