### ISSUE TITLE
I can't decompile .aab

### ISSUE THREAD

**Issue by albetoetecnia** [TamilanPeriyasamy/BundleDecompiler#3]
I'm getting this error:

Exception in thread "main" java.io.IOException: Cannot run program "wget": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:590)
	at java.base/java.lang.Runtime.exec(Runtime.java:414)
	at java.base/java.lang.Runtime.exec(Runtime.java:311)
	at com.bundle.command.CommandExecutor.executeCommand(CommandExecutor.java:67)
	at com.bundle.main.BundleAnalyze.installAndroidTools(BundleAnalyze.java:269)
	at com.bundle.main.BundleAnalyze.<init>(BundleAnalyze.java:25)
	at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:89)
	at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:36)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)

**Comment by 448975515** [comment]
install wget

**Comment by TamilanPeriyasamy** [comment]
Latest version published, check now. **[BundleDecompiler-0.0.2.jar](https://raw.githubusercontent.com/TamilanPeriyasamy/BundleDecompiler/master/build/libs/BundleDecompiler-0.0.2.jar)**.
