### ISSUE TITLE
Not Found \tmp\temp.sh

### ISSUE THREAD

**Issue by 448975515** [TamilanPeriyasamy/BundleDecompiler#4]
Input AppBundle path: E:\tapktool\apktool\haiwai\nflwy\app.aab
tools installing..,C:\Users\Administrator/.tmp/BundleDecompiler
Exception in thread "main" java.io.FileNotFoundException: \tmp\temp.sh
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at com.bundle.command.CommandExecutor.executeCommandShell(CommandExecuto
r.java:31)
        at com.bundle.main.BundleAnalyze.unzipAppBundle(BundleAnalyze.java:244)
        at com.bundle.main.BundleAnalyze.UnpackAppBundle(BundleAnalyze.java:187)

        at com.bundle.main.BundleAnalyze.analyze(BundleAnalyze.java:58)
        at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompil
er.java:90)
        at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:36)

**Comment by TamilanPeriyasamy** [comment]
Latest version published, check now. **[BundleDecompiler-0.0.2.jar](https://raw.githubusercontent.com/TamilanPeriyasamy/BundleDecompiler/master/build/libs/BundleDecompiler-0.0.2.jar)**.

**Comment by widwei** [comment]
> Latest version published, check now. **[BundleDecompiler-0.0.2.jar](https://raw.githubusercontent.com/TamilanPeriyasamy/BundleDecompiler/master/build/libs/BundleDecompiler-0.0.2.jar)**.

Windows system still doesn't work

Exception in thread "main" java.io.FileNotFoundException: \tmp\temp.sh (系统找不到指定的路径。)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at com.bundle.command.CommandExecutor.executeCommandShell(CommandExecutor.java:31)
        at com.bundle.main.BundleAnalyze.unzipAppBundle(BundleAnalyze.java:304)
        at com.bundle.main.BundleAnalyze.UnpackAppBundle(BundleAnalyze.java:247)
        at com.bundle.main.BundleAnalyze.analyze(BundleAnalyze.java:103)
        at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:90)
        at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:35)

**Comment by AvatarGuo** [comment]
get the same error on windows 
E:\chromedownload\0704\test
Exception in thread "main" java.io.FileNotFoundException: \tmp\temp.sh (系统找不到指定的路径。)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at com.bundle.command.CommandExecutor.executeCommandShell(CommandExecutor.java:31)
        at com.bundle.main.BundleAnalyze.unzipAppBundle(BundleAnalyze.java:304)
        at com.bundle.main.BundleAnalyze.UnpackAppBundle(BundleAnalyze.java:247)
        at com.bundle.main.BundleAnalyze.analyze(BundleAnalyze.java:103)
        at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:90)
        at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:35)

**Comment by LexQzim** [comment]
The error is still available ...

`Exception in thread "main" java.io.FileNotFoundException: \tmp\temp.sh (Das System kann den angegebenen Pfad nicht finden)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at com.bundle.command.CommandExecutor.executeCommandShell(CommandExecutor.java:31)
        at com.bundle.main.BundleAnalyze.unzipAppBundle(BundleAnalyze.java:304)
        at com.bundle.main.BundleAnalyze.UnpackAppBundle(BundleAnalyze.java:247)
        at com.bundle.main.BundleAnalyze.analyze(BundleAnalyze.java:103)
        at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:90)
        at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:35)`
