### ISSUE TITLE
Nullpointer exception when decompiling

### ISSUE THREAD

**Issue by jgmGit** [TamilanPeriyasamy/BundleDecompiler#5]
When I try to de-compile it throwing me a null pointer exception. 

I even tried to give the full path to the app-debug.aab, still its the same error.

```
java -jar BundleDecompiler-0.0.1.jar d --in=app-debug.aab --out=extract/
Input AppBundle path: app-debug.aab
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:80)
	at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:36)
```

**Comment by TamilanPeriyasamy** [comment]
Latest version published, check now. **[BundleDecompiler-0.0.2.jar](https://raw.githubusercontent.com/TamilanPeriyasamy/BundleDecompiler/master/build/libs/BundleDecompiler-0.0.2.jar)**.

**Comment by cotedazur** [comment]
Facing the same error as above with  BundleDecompiler-0.0.2.jar. that is just uploaded few hours ago.

**Comment by HiPanda-dev** [comment]
I using BundleDecompiler-0.0.2.jar but I also got the same error

```
java -jar BundleDecompiler-0.0.2.jar decompile --in=app.aab --out=output_dir

Input AppBundle path: app.aab
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:80)
	at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:35)

```

**Comment by TamilanPeriyasamy** [comment]
Please set full file path
Ex:-
**--in=**/Users/apple/Downloads/uk.co.metrobankonline.mobile.apk **--out=**/Users/apple/Downloads/uk.co.metrobankonline.mobile.apk

**Comment by venkhatesh** [comment]
@TamilanPeriyasamy I am getting same error, please can you guide
