### ISSUE TITLE
Decompile procedure stuck at windows 10 

### ISSUE THREAD

**Issue by Dorapazol** [TamilanPeriyasamy/BundleDecompiler#7]
Procedure stuck at
`tools installing..,C:\Users\Dora/.tmp/BundleDecompiler`
after some time android.jar file is created in 
`C:\Users\Dora\.tmp\BundleDecompiler\29.0.2\android.jar`
but no other files shown in /.tmp directory or in specified output directory

Any help appreciated

**Comment by TamilanPeriyasamy** [comment]
Only support **Linux** and **Mac OS**
Try to support windows coming version

**Comment by TamilanPeriyasamy** [comment]
Latest version published, check now. **[BundleDecompiler-0.0.2.jar](https://raw.githubusercontent.com/TamilanPeriyasamy/BundleDecompiler/master/out/BundleDecompiler-0.0.2.jar)**.    ( Only support Linux and Mac OS )

**Comment by Dorapazol** [comment]
Thank you for your responese. Tried latest version, got 

`Exception in thread "main" java.io.FileNotFoundException: \tmp\temp.sh (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at com.bundle.command.CommandExecutor.executeCommandShell(CommandExecutor.java:31)
        at com.bundle.main.BundleAnalyze.unzipAppBundle(BundleAnalyze.java:304)
        at com.bundle.main.BundleAnalyze.UnpackAppBundle(BundleAnalyze.java:247)
        at com.bundle.main.BundleAnalyze.analyze(BundleAnalyze.java:103)
        at com.bundle.main.BundleDecompiler.doRunBundleDecompiler(BundleDecompiler.java:90)
        at com.bundle.main.BundleDecompiler.main(BundleDecompiler.java:35)`

**Comment by TamilanPeriyasamy** [comment]
Sorry Only support Linux and Mac OS

**Comment by Dorapazol** [comment]
Thank you will try in Linux, hope for a windows version soon
